// Code generated by ent, DO NOT EDIT.

package product

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// EdgeImplementationsProduct holds the string denoting the implementationsproduct edge name in mutations.
	EdgeImplementationsProduct = "implementationsProduct"
	// Table holds the table name of the product in the database.
	Table = "products"
	// ImplementationsProductTable is the table that holds the implementationsProduct relation/edge.
	ImplementationsProductTable = "implementations"
	// ImplementationsProductInverseTable is the table name for the Implementation entity.
	// It exists in this package in order to avoid circular dependency with the "implementation" package.
	ImplementationsProductInverseTable = "implementations"
	// ImplementationsProductColumn is the table column denoting the implementationsProduct relation/edge.
	ImplementationsProductColumn = "product_implementations_product"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByImplementationsProductCount orders the results by implementationsProduct count.
func ByImplementationsProductCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newImplementationsProductStep(), opts...)
	}
}

// ByImplementationsProduct orders the results by implementationsProduct terms.
func ByImplementationsProduct(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newImplementationsProductStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newImplementationsProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ImplementationsProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ImplementationsProductTable, ImplementationsProductColumn),
	)
}
