// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "title", Type: field.TypeString},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// RequirementsColumns holds the columns for the "requirements" table.
	RequirementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
	}
	// RequirementsTable holds the schema information for the "requirements" table.
	RequirementsTable = &schema.Table{
		Name:       "requirements",
		Columns:    RequirementsColumns,
		PrimaryKey: []*schema.Column{RequirementsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProductsTable,
		RequirementsTable,
	}
)

func init() {
}
