// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RequirementsColumns holds the columns for the "requirements" table.
	RequirementsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
	}
	// RequirementsTable holds the schema information for the "requirements" table.
	RequirementsTable = &schema.Table{
		Name:       "requirements",
		Columns:    RequirementsColumns,
		PrimaryKey: []*schema.Column{RequirementsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RequirementsTable,
	}
)

func init() {
}
