// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"requirements/ent/implementation"
	"requirements/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImplementationDelete is the builder for deleting a Implementation entity.
type ImplementationDelete struct {
	config
	hooks    []Hook
	mutation *ImplementationMutation
}

// Where appends a list predicates to the ImplementationDelete builder.
func (id *ImplementationDelete) Where(ps ...predicate.Implementation) *ImplementationDelete {
	id.mutation.Where(ps...)
	return id
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (id *ImplementationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, id.sqlExec, id.mutation, id.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (id *ImplementationDelete) ExecX(ctx context.Context) int {
	n, err := id.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (id *ImplementationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(implementation.Table, sqlgraph.NewFieldSpec(implementation.FieldID, field.TypeUUID))
	if ps := id.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, id.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	id.mutation.done = true
	return affected, err
}

// ImplementationDeleteOne is the builder for deleting a single Implementation entity.
type ImplementationDeleteOne struct {
	id *ImplementationDelete
}

// Where appends a list predicates to the ImplementationDelete builder.
func (ido *ImplementationDeleteOne) Where(ps ...predicate.Implementation) *ImplementationDeleteOne {
	ido.id.mutation.Where(ps...)
	return ido
}

// Exec executes the deletion query.
func (ido *ImplementationDeleteOne) Exec(ctx context.Context) error {
	n, err := ido.id.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{implementation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ido *ImplementationDeleteOne) ExecX(ctx context.Context) {
	if err := ido.Exec(ctx); err != nil {
		panic(err)
	}
}
