// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"requirements/ent/predicate"
	"requirements/ent/requirement"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequirementUpdate is the builder for updating Requirement entities.
type RequirementUpdate struct {
	config
	hooks    []Hook
	mutation *RequirementMutation
}

// Where appends a list predicates to the RequirementUpdate builder.
func (ru *RequirementUpdate) Where(ps ...predicate.Requirement) *RequirementUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetTitle sets the "title" field.
func (ru *RequirementUpdate) SetTitle(s string) *RequirementUpdate {
	ru.mutation.SetTitle(s)
	return ru
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (ru *RequirementUpdate) SetNillableTitle(s *string) *RequirementUpdate {
	if s != nil {
		ru.SetTitle(*s)
	}
	return ru
}

// Mutation returns the RequirementMutation object of the builder.
func (ru *RequirementUpdate) Mutation() *RequirementMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RequirementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RequirementUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RequirementUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RequirementUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RequirementUpdate) check() error {
	if v, ok := ru.mutation.Title(); ok {
		if err := requirement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Requirement.title": %w`, err)}
		}
	}
	return nil
}

func (ru *RequirementUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(requirement.Table, requirement.Columns, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Title(); ok {
		_spec.SetField(requirement.FieldTitle, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requirement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RequirementUpdateOne is the builder for updating a single Requirement entity.
type RequirementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequirementMutation
}

// SetTitle sets the "title" field.
func (ruo *RequirementUpdateOne) SetTitle(s string) *RequirementUpdateOne {
	ruo.mutation.SetTitle(s)
	return ruo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (ruo *RequirementUpdateOne) SetNillableTitle(s *string) *RequirementUpdateOne {
	if s != nil {
		ruo.SetTitle(*s)
	}
	return ruo
}

// Mutation returns the RequirementMutation object of the builder.
func (ruo *RequirementUpdateOne) Mutation() *RequirementMutation {
	return ruo.mutation
}

// Where appends a list predicates to the RequirementUpdate builder.
func (ruo *RequirementUpdateOne) Where(ps ...predicate.Requirement) *RequirementUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RequirementUpdateOne) Select(field string, fields ...string) *RequirementUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Requirement entity.
func (ruo *RequirementUpdateOne) Save(ctx context.Context) (*Requirement, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RequirementUpdateOne) SaveX(ctx context.Context) *Requirement {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RequirementUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RequirementUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RequirementUpdateOne) check() error {
	if v, ok := ruo.mutation.Title(); ok {
		if err := requirement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Requirement.title": %w`, err)}
		}
	}
	return nil
}

func (ruo *RequirementUpdateOne) sqlSave(ctx context.Context) (_node *Requirement, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requirement.Table, requirement.Columns, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Requirement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requirement.FieldID)
		for _, f := range fields {
			if !requirement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requirement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Title(); ok {
		_spec.SetField(requirement.FieldTitle, field.TypeString, value)
	}
	_node = &Requirement{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requirement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
