// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"requirements/ent/implementation"
	"requirements/ent/predicate"
	"requirements/ent/requirement"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequirementQuery is the builder for querying Requirement entities.
type RequirementQuery struct {
	config
	ctx                 *QueryContext
	order               []requirement.OrderOption
	inters              []Interceptor
	predicates          []predicate.Requirement
	withImplementations *ImplementationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RequirementQuery builder.
func (rq *RequirementQuery) Where(ps ...predicate.Requirement) *RequirementQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *RequirementQuery) Limit(limit int) *RequirementQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *RequirementQuery) Offset(offset int) *RequirementQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *RequirementQuery) Unique(unique bool) *RequirementQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *RequirementQuery) Order(o ...requirement.OrderOption) *RequirementQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryImplementations chains the current query on the "implementations" edge.
func (rq *RequirementQuery) QueryImplementations() *ImplementationQuery {
	query := (&ImplementationClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(requirement.Table, requirement.FieldID, selector),
			sqlgraph.To(implementation.Table, implementation.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, requirement.ImplementationsTable, requirement.ImplementationsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Requirement entity from the query.
// Returns a *NotFoundError when no Requirement was found.
func (rq *RequirementQuery) First(ctx context.Context) (*Requirement, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{requirement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *RequirementQuery) FirstX(ctx context.Context) *Requirement {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Requirement ID from the query.
// Returns a *NotFoundError when no Requirement ID was found.
func (rq *RequirementQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{requirement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *RequirementQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Requirement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Requirement entity is found.
// Returns a *NotFoundError when no Requirement entities are found.
func (rq *RequirementQuery) Only(ctx context.Context) (*Requirement, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{requirement.Label}
	default:
		return nil, &NotSingularError{requirement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *RequirementQuery) OnlyX(ctx context.Context) *Requirement {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Requirement ID in the query.
// Returns a *NotSingularError when more than one Requirement ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *RequirementQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{requirement.Label}
	default:
		err = &NotSingularError{requirement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *RequirementQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Requirements.
func (rq *RequirementQuery) All(ctx context.Context) ([]*Requirement, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryAll)
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Requirement, *RequirementQuery]()
	return withInterceptors[[]*Requirement](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *RequirementQuery) AllX(ctx context.Context) []*Requirement {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Requirement IDs.
func (rq *RequirementQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryIDs)
	if err = rq.Select(requirement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *RequirementQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *RequirementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryCount)
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*RequirementQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *RequirementQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *RequirementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, ent.OpQueryExist)
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *RequirementQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RequirementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *RequirementQuery) Clone() *RequirementQuery {
	if rq == nil {
		return nil
	}
	return &RequirementQuery{
		config:              rq.config,
		ctx:                 rq.ctx.Clone(),
		order:               append([]requirement.OrderOption{}, rq.order...),
		inters:              append([]Interceptor{}, rq.inters...),
		predicates:          append([]predicate.Requirement{}, rq.predicates...),
		withImplementations: rq.withImplementations.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithImplementations tells the query-builder to eager-load the nodes that are connected to
// the "implementations" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *RequirementQuery) WithImplementations(opts ...func(*ImplementationQuery)) *RequirementQuery {
	query := (&ImplementationClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withImplementations = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Requirement.Query().
//		GroupBy(requirement.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *RequirementQuery) GroupBy(field string, fields ...string) *RequirementGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RequirementGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = requirement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Requirement.Query().
//		Select(requirement.FieldTitle).
//		Scan(ctx, &v)
func (rq *RequirementQuery) Select(fields ...string) *RequirementSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &RequirementSelect{RequirementQuery: rq}
	sbuild.label = requirement.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RequirementSelect configured with the given aggregations.
func (rq *RequirementQuery) Aggregate(fns ...AggregateFunc) *RequirementSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *RequirementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !requirement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *RequirementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Requirement, error) {
	var (
		nodes       = []*Requirement{}
		_spec       = rq.querySpec()
		loadedTypes = [1]bool{
			rq.withImplementations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Requirement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Requirement{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withImplementations; query != nil {
		if err := rq.loadImplementations(ctx, query, nodes,
			func(n *Requirement) { n.Edges.Implementations = []*Implementation{} },
			func(n *Requirement, e *Implementation) { n.Edges.Implementations = append(n.Edges.Implementations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *RequirementQuery) loadImplementations(ctx context.Context, query *ImplementationQuery, nodes []*Requirement, init func(*Requirement), assign func(*Requirement, *Implementation)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Requirement)
	nids := make(map[uuid.UUID]map[*Requirement]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(requirement.ImplementationsTable)
		s.Join(joinT).On(s.C(implementation.FieldID), joinT.C(requirement.ImplementationsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(requirement.ImplementationsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(requirement.ImplementationsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Requirement]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Implementation](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "implementations" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rq *RequirementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *RequirementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(requirement.Table, requirement.Columns, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeUUID))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requirement.FieldID)
		for i := range fields {
			if fields[i] != requirement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *RequirementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(requirement.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = requirement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RequirementGroupBy is the group-by builder for Requirement entities.
type RequirementGroupBy struct {
	selector
	build *RequirementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *RequirementGroupBy) Aggregate(fns ...AggregateFunc) *RequirementGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *RequirementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, ent.OpQueryGroupBy)
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequirementQuery, *RequirementGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *RequirementGroupBy) sqlScan(ctx context.Context, root *RequirementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RequirementSelect is the builder for selecting fields of Requirement entities.
type RequirementSelect struct {
	*RequirementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *RequirementSelect) Aggregate(fns ...AggregateFunc) *RequirementSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *RequirementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, ent.OpQuerySelect)
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RequirementQuery, *RequirementSelect](ctx, rs.RequirementQuery, rs, rs.inters, v)
}

func (rs *RequirementSelect) sqlScan(ctx context.Context, root *RequirementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
