// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"requirements/ent/requirement"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequirementCreate is the builder for creating a Requirement entity.
type RequirementCreate struct {
	config
	mutation *RequirementMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (rc *RequirementCreate) SetTitle(s string) *RequirementCreate {
	rc.mutation.SetTitle(s)
	return rc
}

// SetPath sets the "path" field.
func (rc *RequirementCreate) SetPath(s string) *RequirementCreate {
	rc.mutation.SetPath(s)
	return rc
}

// SetDescription sets the "description" field.
func (rc *RequirementCreate) SetDescription(s string) *RequirementCreate {
	rc.mutation.SetDescription(s)
	return rc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (rc *RequirementCreate) SetNillableDescription(s *string) *RequirementCreate {
	if s != nil {
		rc.SetDescription(*s)
	}
	return rc
}

// SetID sets the "id" field.
func (rc *RequirementCreate) SetID(u uuid.UUID) *RequirementCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *RequirementCreate) SetNillableID(u *uuid.UUID) *RequirementCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// Mutation returns the RequirementMutation object of the builder.
func (rc *RequirementCreate) Mutation() *RequirementMutation {
	return rc.mutation
}

// Save creates the Requirement in the database.
func (rc *RequirementCreate) Save(ctx context.Context) (*Requirement, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RequirementCreate) SaveX(ctx context.Context) *Requirement {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RequirementCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RequirementCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RequirementCreate) defaults() {
	if _, ok := rc.mutation.Description(); !ok {
		v := requirement.DefaultDescription
		rc.mutation.SetDescription(v)
	}
	if _, ok := rc.mutation.ID(); !ok {
		v := requirement.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RequirementCreate) check() error {
	if _, ok := rc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Requirement.title"`)}
	}
	if v, ok := rc.mutation.Title(); ok {
		if err := requirement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Requirement.title": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Requirement.path"`)}
	}
	if v, ok := rc.mutation.Path(); ok {
		if err := requirement.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Requirement.path": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Requirement.description"`)}
	}
	return nil
}

func (rc *RequirementCreate) sqlSave(ctx context.Context) (*Requirement, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RequirementCreate) createSpec() (*Requirement, *sqlgraph.CreateSpec) {
	var (
		_node = &Requirement{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(requirement.Table, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeUUID))
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.Title(); ok {
		_spec.SetField(requirement.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := rc.mutation.Path(); ok {
		_spec.SetField(requirement.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := rc.mutation.Description(); ok {
		_spec.SetField(requirement.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	return _node, _spec
}

// RequirementCreateBulk is the builder for creating many Requirement entities in bulk.
type RequirementCreateBulk struct {
	config
	err      error
	builders []*RequirementCreate
}

// Save creates the Requirement entities in the database.
func (rcb *RequirementCreateBulk) Save(ctx context.Context) ([]*Requirement, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Requirement, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequirementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RequirementCreateBulk) SaveX(ctx context.Context) []*Requirement {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RequirementCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RequirementCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
