// Code generated by ent, DO NOT EDIT.

package ent

import (
	"requirements/ent/requirement"
	"requirements/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	requirementFields := schema.Requirement{}.Fields()
	_ = requirementFields
	// requirementDescTitle is the schema descriptor for title field.
	requirementDescTitle := requirementFields[0].Descriptor()
	// requirement.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	requirement.TitleValidator = requirementDescTitle.Validators[0].(func(string) error)
}
