// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Requirement is the predicate function for requirement builders.
type Requirement func(*sql.Selector)
