// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Implementation is the predicate function for implementation builders.
type Implementation func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Requirement is the predicate function for requirement builders.
type Requirement func(*sql.Selector)
